"""Constants for open3e."""

DOMAIN = "open3e"

MQTT_TOPIC_KEY = "mqtt_topic"
MQTT_TOPIC_DEFAULT = "open3e"
MQTT_CMD_KEY = "mqtt_cmnd"
MQTT_CMD_DEFAULT = "open3e/cmnd"
MQTT_SYSTEM_TOPIC = "system"
MQTT_SYSTEM_PAYLOAD = '{"mode":"system"}'

VIESSMANN_TEMP_HEATING_MIN = 3
VIESSMANN_TEMP_HEATING_MAX = 37

VIESSMANN_TEMP_DHW_MIN = 10
VIESSMANN_TEMP_DHW_MAX = 60
